# Generated by Django 3.0.5 on 2025-05-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Price')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('cd', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
