# Generated by Django 4.2.21 on 2025-06-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_userinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
