# Generated by Django 4.2.21 on 2025-06-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_userinteraction_city_userinteraction_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='region',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='user_agent',
        ),
    ]
